# Generated by Django 5.0.3 on 2024-03-24 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousThematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('thematique_parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.thematiques')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
