# Generated by Django 5.0.3 on 2024-03-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sousthematique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousthematique',
            name='thematique_parente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_thematiques', to='pages.thematiques'),
        ),
    ]
