# Generated by Django 5.0.3 on 2024-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
