# Generated by Django 5.0.3 on 2024-04-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_product_delete_produit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information_text", models.TextField()),
                ("csv_file", models.FileField(upload_to="csv_files/")),
                (
                    "soustheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="pages.sousthematique",
                    ),
                ),
            ],
        ),
    ]
