# Generated by Django 5.0.3 on 2024-04-16 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_informations_csv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informations",
            name="csv_file",
        ),
    ]
