# Generated by Django 5.0.3 on 2024-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_remove_informations_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="informations",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="csv_files/"),
        ),
    ]
