# Generated by Django 5.0.3 on 2024-04-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_informations_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informations",
            name="soustheme",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="pages.sousthematique",
            ),
        ),
    ]
