# Generated by Django 5.0.3 on 2024-04-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_alter_informations_soustheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousthematique",
            name="thematique_parente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.thematiques"
            ),
        ),
    ]
