# Generated by Django 5.0.3 on 2024-05-01 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_alter_sousthematique_thematique_parente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
