# Generated by Django 5.0.3 on 2024-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_alter_sousthematique_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousthematique",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="thematiques",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
