# Generated by Django 5.0.3 on 2024-05-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_sousthematique_description_sous_thematique"),
    ]

    operations = [
        migrations.AddField(
            model_name="sousthematique",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="csv_files/"),
        ),
        migrations.DeleteModel(
            name="Informations",
        ),
    ]
