# Generated by Django 5.0.3 on 2024-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_sousthematique_csv_file_delete_informations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousthematique",
            name="description_sous_thematique",
            field=models.TextField(blank=True, default="Texte descriptif"),
        ),
    ]
