# Generated by Django 5.0.3 on 2024-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0020_alter_sousthematique_description_sous_thematique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousthematique",
            name="description_sous_thematique",
            field=models.TextField(default="Description par défaut"),
        ),
    ]
