# Generated by Django 5.0.3 on 2024-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_alter_sousthematique_description_sous_thematique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousthematique",
            name="description_sous_thematique",
            field=models.TextField(blank=True, default="Description par défaut"),
        ),
    ]
