# Generated by Django 5.0.3 on 2024-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_alter_sousthematique_description_sous_thematique"),
    ]

    operations = [
        migrations.AddField(
            model_name="sousthematique",
            name="periodicite",
            field=models.CharField(default="2024", max_length=200),
        ),
    ]
