# Generated by Django 5.0.3 on 2024-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0024_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(upload_to="static/images")),
                ("date_ajout", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_ajout"],
            },
        ),
    ]
