# Generated by Django 5.0.3 on 2024-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_actualite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematiques',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
