# Generated by Django 4.1.7 on 2024-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_thematiques_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousthematique',
            name='periodicite',
            field=models.IntegerField(default=2024),
        ),
    ]
