# Generated by Django 4.2.5 on 2024-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_sousthematique_periodicite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
