# Generated by Django 5.1.4 on 2025-01-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_actualite_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualite',
        ),
    ]
