# Generated by Django 5.1.4 on 2025-01-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_delete_actualite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thematiques',
            table='Thematiques',
        ),
    ]
