# Generated by Django 5.1.4 on 2025-01-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_thematiques_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thematiques',
            table=None,
        ),
    ]
