# Generated by Django 5.1.4 on 2025-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_alter_sousthematique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousthematique',
            name='titre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
