# Generated by Django 5.1.4 on 2025-01-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
