# Generated by Django 5.1.4 on 2025-01-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_emailverificationtoken_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='email_verified',
        ),
    ]
