# Generated by Django 4.2.5 on 2023-09-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicite', models.IntegerField()),
                ('data', models.CharField(default='Non renseigné', max_length=100)),
            ],
        ),
    ]
