# Generated by Django 4.2.5 on 2023-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='data',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='periodicite',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
    ]
