# Generated by Django 4.2.5 on 2023-09-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_datatable_data_alter_datatable_periodicite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'ordering': ['-data']},
        ),
    ]
